name: Build KanaDetector

on:
  push:
    branches: [ main ]
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches: [ main ]
    
env:
  configuration: Release
  productNamespacePrefix: "MyNihongo"
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        
    - name: Install .NET 5
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
          
    - name: NuGet restore
      run: | 
        dotnet restore MyNihongo.KanaDetector.csproj
      working-directory: src
      
    - name: Build
      run: dotnet build Nihongo.KanaDetector.csproj -c RELEASE -v
      working-directory: src
      
    - name: Run tests and generate coverage
      uses: glennawatson/coverlet-msbuild@v1
      with:
        project-files: 'tests/**/*Tests*.csproj'
        no-build: true
        output-format: cobertura
        configuration: 'RELEASE'
